[package]
name = "yde-launcher"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = { path = "./crates/iced", features = ["image"] }
iced_core = { path = "./crates/iced/core" }
anyhow = "1.0"
rayon = "1.11.0"
freedesktop_entry_parser = "2.0.1"
once_cell = "1.18.0"
fuzzy-matcher = "0.3.7"
