[package]
name = "yde-launcher"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
rayon = "1.11.0"
freedesktop_entry_parser = "2.0.1"
once_cell = "1.18.0"
fuzzy-matcher = "0.3.7"
libc = "0.2.177"
regex = "1.12.2"
shell-words = "1.1.0"
gpui = "0.2.2"
gpui-component = "0.3.1"
